### ISSUE TITLE
love your tabline, struggling to adapt it

### ISSUE THREAD

**Issue by DanCardin** [haorenW1025/dotfiles#2]
Hey! I really liked the look of your status/tab line, but I dont really use tabs much. So I largely copy-pasta-d your status-line.lua and swapped out for the appropriate buffer methods (and dealt with a bunch of random hidden buffer nonsense etc,etc), and [it seems to work okay now.](https://github.com/DanCardin/dotfiles/blob/master/config/nvim/lua/status-line.lua)

Main problem is once you get to a certain number of items relative to the width of vim, the currently active tab can scroll completely off screen. Curious if you've got any quick ideas on how to address that?

secondary, smaller issue being that the drawing is lazier than the statusline. Might be an issue I created with my changes (plus i made the tabline follow the colors of the statusline on mode changes), but it often is stuck on the previous state visually until i do something that would cause it to redraw.

Feel free to close this, just figured I would ask since you're clearly a lot more familiar with the vim apis/lua than I am

**Comment by haorenW1025** [comment]
Main problem: Unfortunately no, maybe take a loot at lightline or other statusline plugin and see if they have the same issue will help?
Seconde question: I haven't noticed the redraw issues... mainly because I doesn't do a lot of things with tabline.

Sorry for not being very helpful. This dotfile is mainly aimed for myself so maybe it would have so issues here and there. Sorry for the inconvenience!

**Comment by DanCardin** [comment]
np, just figured i would ask!
